name: Check and Rename YAML files

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  check_and_rename_yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml packaging
      
      # Run the reformat action
      - name: Reformat YAML Files
        uses: credfeto/action-yaml-format@v1.3.2

      - name: Check and rename YAML files
        run: |
          python check_and_rename_yaml.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Bump version by check_and_rename_yaml action"
          git push
