name: Check and Rename YAML files

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  check_and_rename_yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml packaging

      - name: Check and rename YAML files
        run: |
          python check_and_rename_yaml.py
